version: 2


build:
   os: ubuntu-20.04
   tools:
     python: "3.7"

python:
   # only use the packages specified in setup.py
   system_packages: false

   install:
      - method: pip
        path: .
        extra_requirements:
          - doc
