name: readthedocs
channels:
    - defaults
    - conda-forge
dependencies:
  - python=3.7
  - pandas
  - matplotlib
  - numpy
  - shapely # Should be installed with conda
  - sphinx
  - pip:
        - pvlib
        - myst-nb
        - sphinx-book-theme
